import Image from "next/image";
import Head from 'next/head';


export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 to-black text-white flex flex-col items-center justify-center">
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
        <div className="absolute top-5 right-10">
          <a href="#" className="text-lg text-gray-400 hover:text-white">Sign in</a>
        </div>
        <div className="absolute top-5 left-10">
          <a href="#" className="text-lg text-blue-400 hover:text-blue-600">Get Started</a>
        </div>
        <h1 className="text-6xl font-bold mb-4">
          Where the world builds <span className="text-blue-400">software</span>
        </h1>
        <p className="mt-3 text-2xl">
          Our landing page template works on all devices, so you only have to set it up once, and get beautiful results forever.
        </p>
        <div className="mt-8 flex space-x-4">
          <a href="#" className="bg-blue-500 text-white px-6 py-3 rounded-md text-lg font-semibold hover:bg-blue-600">
            Get Started For Free
          </a>
          <a href="#" className="bg-gray-700 text-white px-6 py-3 rounded-md text-lg font-semibold hover:bg-gray-600">
            Explore Docs
          </a>
        </div>
      </main>

      <footer className="flex items-center justify-center w-full h-24 border-t">
        <a
          className="flex items-center justify-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          copyright@2024
          <img src="/vercel.svg" alt="Vercel Logo" className="h-4 ml-2" />
        </a>
      </footer>
    </div>
  );
}
